apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-profile-demo-cpu-metrics
  namespace: gadget
  labels:
    type: gadget-instance
    name: cpu-profile-demo-cpu-metrics
  annotations:
    gadgetImage: "top_process"
    gadgetTags: "cpu,metrics"
    gadgetTimeout: "0"
    gadgetLogLevel: "0"
    gadgetNodes: ""
data:
  interval: "30s"
  operator.KubeManager.all-namespaces: "true"
  operator.filter.filter: "k8s.namespace~cpu-profile"
  operator.oci.annotate: "processes:metrics.collect=true,processes.k8s.namespace:metrics.type=key,processes.cpuUsage:metrics.type=gauge"
  operator.otel-metrics.otel-metrics-name: "processes:top-process-cpu"
