apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-profile-demo
  namespace: cpu-profile-baseline
  labels:
    app.kubernetes.io/name: cpu-profile-demo
    app.kubernetes.io/instance: baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cpu-profile-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cpu-profile-demo
        app.kubernetes.io/component: application
        app.kubernetes.io/instance: baseline
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: application
          image: ghcr.io/mqasimsarfraz/python-cpu-profiling-demo:latest
          imagePullPolicy: Always
          env:
            - name: DUPLICATE_IMPLEMENTATION
              value: baseline
            - name: DUPLICATE_INPUT_SIZE
              value: "3000"
            - name: SORT_INPUT_SIZE
              value: "750000"
            - name: WORK_INTERVAL_SECONDS
              value: "1"
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-profile-demo
  namespace: cpu-profile-optimized
  labels:
    app.kubernetes.io/name: cpu-profile-demo
    app.kubernetes.io/instance: optimized
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cpu-profile-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cpu-profile-demo
        app.kubernetes.io/component: application
        app.kubernetes.io/instance: optimized
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: application
          image: ghcr.io/mqasimsarfraz/python-cpu-profiling-demo:latest
          imagePullPolicy: Always
          env:
            - name: DUPLICATE_IMPLEMENTATION
              value: optimized
            - name: DUPLICATE_INPUT_SIZE
              value: "3000"
            - name: SORT_INPUT_SIZE
              value: "750000"
            - name: WORK_INTERVAL_SECONDS
              value: "1"
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
