apiVersion: v1
kind: Service
metadata:
  name: cpu-profile-demo
  namespace: cpu-profile-demo
spec:
  selector:
    app.kubernetes.io/name: cpu-profile-demo
  ports:
    - name: http
      port: 80
      targetPort: http
